import React, { useState, useEffect } from 'react';
import moment from 'moment';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';
import Select from 'react-select';

// Define colors for each stat
const statColors = {
  'Adjusted Shooting': {
    'Shooting % FG': '#FF5733',
    'Shooting % 2P': '#33FF57',
    'Shooting % 3P': '#3357FF',
    'Shooting % eFG': '#F3FF33',
    'Shooting % FT': '#FF33F3',
    'Shooting % TS': '#33FFF3',
    'Shooting % FTr': '#FF8C33',
    'Shooting % 3PAr': '#8C33FF',
    'League Shooting % FG': '#33FF8C',
    'League Shooting % 2P': '#FF33A2',
    'League Shooting % 3P': '#A233FF',
    'League Shooting % eFG': '#33A2FF',
    'League Shooting % FT': '#A2FF33',
    'League Shooting % TS': '#F8C300',
    'League Shooting % FTr': '#00F8C3',
    'League Shooting % 3PAr': '#C300F8',
  },
  'Totals': {
    'G': '#FFC300',
    'GS': '#FF5733',
    'MP': '#33FF57',
    'FG': '#3357FF',
    'FGA': '#FF33F3',
    'FG%': '#33FFF3',
    '3P': '#FF8C33',
    '3PA': '#8C33FF',
    '3P%': '#33FF8C',
    '2P': '#FF33A2',
    '2PA': '#A233FF',
    '2P%': '#33A2FF',
    'eFG%': '#A2FF33',
    'FT': '#F8C300',
    'FTA': '#00F8C3',
    'FT%': '#C300F8',
    'ORB': '#FFC300',
    'DRB': '#FF5733',
    'TRB': '#33FF57',
    'AST': '#3357FF',
    'STL': '#FF33F3',
    'BLK': '#33FFF3',
    'TOV': '#FF8C33',
    'PF': '#8C33FF',
    'PTS': '#33FF8C',
  },
  'Advanced': {
    'G': '#FF5733',
    'MP': '#33FF57',
    'PER': '#3357FF',
    'TS%': '#FF33F3',
    '3PAr': '#33FFF3',
    'FTr': '#FF8C33',
    'ORB%': '#8C33FF',
    'DRB%': '#33FF8C',
    'TRB%': '#FF33A2',
    'AST%': '#A233FF',
    'STL%': '#33A2FF',
    'BLK%': '#A2FF33',
    'TOV%': '#F8C300',
    'USG%': '#00F8C3',
    'OWS': '#C300F8',
    'DWS': '#FFC300',
    'WS': '#FF5733',
    'WS/48': '#33FF57',
    'OBPM': '#3357FF',
    'DBPM': '#FF33F3',
    'BPM': '#33FFF3',
    'VORP': '#FF8C33',
  },
  'Highs': {
    'Game Highs MP': '#33FF57',
    'Game Highs FG': '#3357FF',
    'Game Highs FGA': '#FF33F3',
    'Game Highs 3P': '#33FFF3',
    'Game Highs 3PA': '#FF8C33',
    'Game Highs 2P': '#8C33FF',
    'Game Highs 2PA': '#33FF8C',
    'Game Highs FT': '#FF33A2',
    'Game Highs FTA': '#A233FF',
    'Game Highs ORB': '#33A2FF',
    'Game Highs DRB': '#A2FF33',
    'Game Highs TRB': '#F8C300',
    'Game Highs AST': '#00F8C3',
    'Game Highs STL': '#C300F8',
    'Game Highs BLK': '#FFC300',
    'Game Highs TOV': '#FF5733',
    'Game Highs PF': '#33FF57',
    'Game Highs PTS': '#3357FF',
    'Game Highs GmSc': '#FF33F3',
  },
  'Individual Game Data': {
    'MP': '#33FF57',
    'FG': '#3357FF',
    'FGA': '#FF33F3',
    'FG%': '#33FFF3',
    '3P': '#FF8C33',
    '3PA': '#8C33FF',
    '3P%': '#33FF8C',
    'FT': '#FF33A2',
    'FTA': '#A233FF',
    'FT%': '#33A2FF',
    'ORB': '#A2FF33',
    'DRB': '#F8C300',
    'TRB': '#00F8C3',
    'AST': '#C300F8',
    'STL': '#FFC300',
    'BLK': '#FF5733',
    'TOV': '#33FF57',
    'PF': '#3357FF',
    'PTS': '#FF33F3',
    'GmSc': '#33FFF3',
    '+/-': '#FF8C33',
  },
  'Per Game': {
    'G': '#FF5733',
    'GS': '#33FF57',
    'MP': '#3357FF',
    'FG': '#FF33F3',
    'FGA': '#33FFF3',
    'FG%': '#FF8C33',
    '3P': '#8C33FF',
    '3PA': '#33FF8C',
    '3P%': '#FF33A2',
    '2P': '#A233FF',
    '2PA': '#33A2FF',
    '2P%': '#A2FF33',
    'eFG%': '#F8C300',
    'FT': '#00F8C3',
    'FTA': '#C300F8',
    'FT%': '#FFC300',
    'ORB': '#FF5733',
    'DRB': '#33FF57',
    'TRB': '#3357FF',
    'AST': '#FF33F3',
    'STL': '#33FFF3',
    'BLK': '#FF8C33',
    'TOV': '#8C33FF',
    'PF': '#33FF8C',
    'PTS': '#FF33A2',
  },
  'Per 36 Minutes': {
    'G': '#FF5733',
    'GS': '#33FF57',
    'MP': '#3357FF',
    'FG': '#FF33F3',
    'FGA': '#33FFF3',
    'FG%': '#FF8C33',
    '3P': '#8C33FF',
    '3PA': '#33FF8C',
    '3P%': '#FF33A2',
    '2P': '#A233FF',
    '2PA': '#33A2FF',
    '2P%': '#A2FF33',
    'FT': '#F8C300',
    'FTA': '#00F8C3',
    'FT%': '#C300F8',
    'ORB': '#FFC300',
    'DRB': '#FF5733',
    'TRB': '#33FF57',
    'AST': '#3357FF',
    'STL': '#FF33F3',
    'BLK': '#33FFF3',
    'TOV': '#FF8C33',
    'PF': '#8C33FF',
    'PTS': '#33FF8C',
  },
  'Per Possesion': {
    'G': '#FF5733',
    'GS': '#33FF57',
    'MP': '#3357FF',
    'FG': '#FF33F3',
    'FGA': '#33FFF3',
    'FG%': '#FF8C33',
    '3P': '#8C33FF',
    '3PA': '#33FF8C',
    '3P%': '#FF33A2',
    '2P': '#A233FF',
    '2PA': '#33A2FF',
    '2P%': '#A2FF33',
    'FT': '#F8C300',
    'FTA': '#00F8C3',
    'FT%': '#C300F8',
    'ORB': '#FFC300',
    'DRB': '#FF5733',
    'TRB': '#33FF57',
    'AST': '#3357FF',
    'STL': '#FF33F3',
    'BLK': '#33FFF3',
    'TOV': '#FF8C33',
    'PF': '#8C33FF',
    'PTS': '#33FF8C',
    'ORtg': '#FF33A2',
    'DRtg': '#A233FF',
  },
  'Play By Play': {
    'G': '#FF5733',
    'MP': '#33FF57',
    'Position Estimate PF%': '#3357FF',
    'Position Estimate C%': '#FF33F3',
    'Position Estimate SF%': '#33FFF3',
    'Position Estimate SG%': '#FF8C33',
    'Position Estimate PG%': '#8C33FF',
    'FGA': '#33FF8C',
    'FGM': '#FF33A2',
    'FG%': '#A233FF',
    'FG3M': '#33A2FF',
    'FG3A': '#A2FF33',
    'FG3%': '#F8C300',
    'FTM': '#00F8C3',
    'FTA': '#C300F8',
    'FT%': '#FFC300',
    'ORB': '#FF5733',
    'DRB': '#33FF57',
    'TRB': '#3357FF',
    'AST': '#FF33F3',
    'STL': '#33FFF3',
    'BLK': '#FF8C33',
    'TOV': '#8C33FF',
    'PF': '#33FF8C',
    'PTS': '#FF33A2',
    '+/-': '#A233FF',
    'Fouls': '#33A2FF',
    'Tech Foul': '#A2FF33',
    'Personal Foul': '#F8C300',
    'Team Foul': '#00F8C3',
    'Team Technical': '#C300F8',
  },
  'Playoffs': {
    "Totals G": "#FF5733",
    "Totals W": "#33FF57",
    "Totals L": "#3357FF",
    "Totals MP": "#FF33F3",
    "Totals FG": "#33FFF3",
    "Totals FGA": "#FF8C33",
    "Totals 3P": "#8C33FF",
    "Totals 3PA": "#33FF8C",
    "Totals FT": "#FF33A2",
    "Totals FTA": "#A233FF",
    "Totals ORB": "#33A2FF",
    "Totals TRB": "#A2FF33",
    "Totals AST": "#F8C300",
    "Totals STL": "#00F8C3",
    "Totals BLK": "#C300F8",
    "Totals TOV": "#FFC300",
    "Totals PF": "#FF5733",
    "Totals PTS": "#33FF57",
    "Shooting FG%": "#3357FF",
    "Shooting FT%": "#FF33F3",
    "Per Game MP": "#33FFF3",
    "Per Game PTS": "#FF8C33",
    "Per Game TRB": "#8C33FF",
    "Per Game AST": "#33FF8C"
  },
  'Shooting': {
    'FG': '#FF5733',
    'FGA': '#33FF57',
    'FG%': '#3357FF',
    'FG3': '#FF33F3',
    'FG3A': '#33FFF3',
    'FG3%': '#FF8C33',
    'FG2': '#8C33FF',
    'FG2A': '#33FF8C',
    'FG2%': '#FF33A2',
    'FT': '#A233FF',
    'FTA': '#33A2FF',
    'FT%': '#A2FF33',
    'TS%': '#F8C300',
    'eFG%': '#00F8C3',
    '3PAr': '#C300F8',
    'FTr': '#FFC300',
    'FG% Adj': '#FF5733',
  },
};


const statOptions = {
  'Adjusted Shooting': [
    { value: 'Shooting % FG', label: 'FG %' },
    { value: 'Shooting % 2P', label: '2P %' },
    { value: 'Shooting % 3P', label: '3P %' },
    { value: 'Shooting % eFG', label: 'eFG %' },
    { value: 'Shooting % FT', label: 'FT %' },
    { value: 'Shooting % TS', label: 'TS %' },
    { value: 'Shooting % FTr', label: 'Free Throw attempt ratio' },
    { value: 'Shooting % 3PAr', label: '3PT attempt ratio' },
    { value: 'League Shooting % FG', label: 'League FG %' },
    { value: 'League Shooting % 2P', label: 'League 2P %' },
    { value: 'League Shooting % 3P', label: 'League 3P %' },
    { value: 'League Shooting % eFG', label: 'League eFG %' },
    { value: 'League Shooting % FT', label: 'League FT %' },
    { value: 'League Shooting % TS', label: 'League TS %' },
    { value: 'League Shooting % FTr', label: 'League Free Throw attempt ratio' },
    { value: 'League Shooting % 3PAr', label: 'League 3PT attempt ratio' },
  ],
  'Totals': [
    { "value": "G", label: "Games" },
    { "value": "GS", label: "Games Started" },
    { "value": "MP", label: "Minutes Played" },
    { "value": "FG", label: "Field Goals Made" },
    { "value": "FGA", label: "Field Goals Attempted" },
    { "value": "FG%", label: "Field Goal Percentage" },
    { "value": "3P", label: "Three-Point Field Goals Made" },
    { "value": "3PA", label: "Three-Point Field Goals Attempted" },
    { "value": "3P%", label: "Three-Point Field Goal Percentage" },
    { "value": "2P", label: "Two-Point Field Goals Made" },
    { "value": "2PA", label: "Two-Point Field Goals Attempted" },
    { "value": "2P%", label: "Two-Point Field Goal Percentage" },
    { "value": "eFG%", label: "Effective Field Goal Percentage" },
    { "value": "FT", label: "Free Throws Made" },
    { "value": "FTA", label: "Free Throws Attempted" },
    { "value": "FT%", label: "Free Throw Percentage" },
    { "value": "ORB", label: "Offensive Rebounds" },
    { "value": "DRB", label: "Defensive Rebounds" },
    { "value": "TRB", label: "Total Rebounds" },
    { "value": "AST", label: "Assists" },
    { "value": "STL", label: "Steals" },
    { "value": "BLK", label: "Blocks" },
    { "value": "TOV", label: "Turnovers" },
    { "value": "PF", label: "Personal Fouls" },
    { "value": "PTS", label: "Points" }
  ],
  'Advanced': [
    { "value": "G", label: "Games" },
    { "value": "MP", label: "Minutes Played" },
    { "value": "PER", label: "Player Efficiency Rating" },
    { "value": "TS%", label: "True Shooting Percentage" },
    { "value": "3PAr", label: "Three-Point Attempt Rate" },
    { "value": "FTr", label: "Free Throw Rate" },
    { "value": "ORB%", label: "Offensive Rebound Percentage" },
    { "value": "DRB%", label: "Defensive Rebound Percentage" },
    { "value": "TRB%", label: "Total Rebound Percentage" },
    { "value": "AST%", label: "Assist Percentage" },
    { "value": "STL%", label: "Steal Percentage" },
    { "value": "BLK%", label: "Block Percentage" },
    { "value": "TOV%", label: "Turnover Percentage" },
    { "value": "USG%", label: "Usage Percentage" },
    { "value": "OWS", label: "Offensive Win Shares" },
    { "value": "DWS", label: "Defensive Win Shares" },
    { "value": "WS", label: "Win Shares" },
    { "value": "WS/48", label: "Win Shares per 48 Minutes" },
    { "value": "OBPM", label: "Offensive Box Plus/Minus" },
    { "value": "DBPM", label: "Defensive Box Plus/Minus" },
    { "value": "BPM", label: "Box Plus/Minus" },
    { "value": "VORP", label: "Value Over Replacement Player" }
  ],
  'Highs': [
    { "value": "Game Highs FG", label: "Field Goals Made" },
    { "value": "Game Highs FGA", label: "Field Goals Attempted" },
    { "value": "Game Highs 3P", label: "Three-Point Field Goals Made" },
    { "value": "Game Highs 3PA", label: "Three-Point Field Goals Attempted" },
    { "value": "Game Highs 2P", label: "Two-Point Field Goals Made" },
    { "value": "Game Highs 2PA", label: "Two-Point Field Goals Attempted" },
    { "value": "Game Highs FT", label: "Free Throws Made" },
    { "value": "Game Highs FTA", label: "Free Throws Attempted" },
    { "value": "Game Highs ORB", label: "Offensive Rebounds" },
    { "value": "Game Highs DRB", label: "Defensive Rebounds" },
    { "value": "Game Highs TRB", label: "Total Rebounds" },
    { "value": "Game Highs AST", label: "Assists" },
    { "value": "Game Highs STL", label: "Steals" },
    { "value": "Game Highs BLK", label: "Blocks" },
    { "value": "Game Highs TOV", label: "Turnovers" },
    { "value": "Game Highs PF", label: "Personal Fouls" },
    { "value": "Game Highs PTS", label: "Points" },
    { "value": "Game Highs GmSc", label: "Game Score" }
  ],
  'Individual Game Data': [
    { "value": "MP", label: "Minutes Played" },
    { "value": "FG", label: "Field Goals Made" },
    { "value": "FGA", label: "Field Goals Attempted" },
    { "value": "FG%", label: "Field Goal Percentage" },
    { "value": "3P", label: "Three-Point Field Goals Made" },
    { "value": "3PA", label: "Three-Point Field Goals Attempted" },
    { "value": "3P%", label: "Three-Point Field Goal Percentage" },
    { "value": "FT", label: "Free Throws Made" },
    { "value": "FTA", label: "Free Throws Attempted" },
    { "value": "FT%", label: "Free Throw Percentage" },
    { "value": "ORB", label: "Offensive Rebounds" },
    { "value": "DRB", label: "Defensive Rebounds" },
    { "value": "TRB", label: "Total Rebounds" },
    { "value": "AST", label: "Assists" },
    { "value": "STL", label: "Steals" },
    { "value": "BLK", label: "Blocks" },
    { "value": "TOV", label: "Turnovers" },
    { "value": "PF", label: "Personal Fouls" },
    { "value": "PTS", label: "Points" },
    { "value": "GmSc", label: "Game Score" },
    { "value": "+/-", label: "Plus/Minus" }
  ],
  'Per Game': [
    { "value": "G", label: "Games" },
    { "value": "GS", label: "Games Started" },
    { "value": "MP", label: "Minutes Played" },
    { "value": "FG", label: "Field Goals Made" },
    { "value": "FGA", label: "Field Goals Attempted" },
    { "value": "FG%", label: "Field Goal Percentage" },
    { "value": "3P", label: "Three-Point Field Goals Made" },
    { "value": "3PA", label: "Three-Point Field Goals Attempted" },
    { "value": "3P%", label: "Three-Point Field Goal Percentage" },
    { "value": "2P", label: "Two-Point Field Goals Made" },
    { "value": "2PA", label: "Two-Point Field Goals Attempted" },
    { "value": "2P%", label: "Two-Point Field Goal Percentage" },
    { "value": "eFG%", label: "Effective Field Goal Percentage" },
    { "value": "FT", label: "Free Throws Made" },
    { "value": "FTA", label: "Free Throws Attempted" },
    { "value": "FT%", label: "Free Throw Percentage" },
    { "value": "ORB", label: "Offensive Rebounds" },
    { "value": "DRB", label: "Defensive Rebounds" },
    { "value": "TRB", label: "Total Rebounds" },
    { "value": "AST", label: "Assists" },
    { "value": "STL", label: "Steals" },
    { "value": "BLK", label: "Blocks" },
    { "value": "TOV", label: "Turnovers" },
    { "value": "PF", label: "Personal Fouls" },
    { "value": "PTS", label: "Points" }
  ],
  'Per 36 Minutes': [
    { "value": "FG", label: "Field Goals Made" },
    { "value": "FGA", label: "Field Goals Attempted" },
    { "value": "FG%", label: "Field Goal Percentage" },
    { "value": "3P", label: "Three-Point Field Goals Made" },
    { "value": "3PA", label: "Three-Point Field Goals Attempted" },
    { "value": "3P%", label: "Three-Point Field Goal Percentage" },
    { "value": "2P", label: "Two-Point Field Goals Made" },
    { "value": "2PA", label: "Two-Point Field Goals Attempted" },
    { "value": "2P%", label: "Two-Point Field Goal Percentage" },
    { "value": "FT", label: "Free Throws Made" },
    { "value": "FTA", label: "Free Throws Attempted" },
    { "value": "FT%", label: "Free Throw Percentage" },
    { "value": "ORB", label: "Offensive Rebounds" },
    { "value": "DRB", label: "Defensive Rebounds" },
    { "value": "TRB", label: "Total Rebounds" },
    { "value": "AST", label: "Assists" },
    { "value": "STL", label: "Steals" },
    { "value": "BLK", label: "Blocks" },
    { "value": "TOV", label: "Turnovers" },
    { "value": "PF", label: "Personal Fouls" },
    { "value": "PTS", label: "Points" }
  ],
  'Per Possesion': [
    { "value": "G", label: "Games" },
    { "value": "GS", label: "Games Started" },
    { "value": "MP", label: "Minutes Played" },
    { "value": "FG", label: "Field Goals Made" },
    { "value": "FGA", label: "Field Goals Attempted" },
    { "value": "FG%", label: "Field Goal Percentage" },
    { "value": "3P", label: "Three-Point Field Goals Made" },
    { "value": "3PA", label: "Three-Point Field Goals Attempted" },
    { "value": "3P%", label: "Three-Point Field Goal Percentage" },
    { "value": "2P", label: "Two-Point Field Goals Made" },
    { "value": "2PA", label: "Two-Point Field Goals Attempted" },
    { "value": "2P%", label: "Two-Point Field Goal Percentage" },
    { "value": "FT", label: "Free Throws Made" },
    { "value": "FTA", label: "Free Throws Attempted" },
    { "value": "FT%", label: "Free Throw Percentage" },
    { "value": "ORB", label: "Offensive Rebounds" },
    { "value": "DRB", label: "Defensive Rebounds" },
    { "value": "TRB", label: "Total Rebounds" },
    { "value": "AST", label: "Assists" },
    { "value": "STL", label: "Steals" },
    { "value": "BLK", label: "Blocks" },
    { "value": "TOV", label: "Turnovers" },
    { "value": "PF", label: "Personal Fouls" },
    { "value": "PTS", label: "Points" },
    { "value": "ORtg", label: "Offensive Rating" },
    { "value": "DRtg", label: "Defensive Rating" }
  ],
  'Play By Play': [
    { "value": "G", label: "Games" },
    { "value": "MP", label: "Minutes Played" },
    { "value": "Position Estimate PF%", label: "Position Estimate Power Forward Percentage" },
    { "value": "Position Estimate C%", label: "Position Estimate Center Percentage" },
    { "value": "+/- Per 100 Poss. OnCourt", label: "Plus/Minus Per 100 Possessions On Court" },
    { "value": "+/- Per 100 Poss. On-Off", label: "Plus/Minus Per 100 Possessions On-Off" },
    { "value": "Turnovers BadPass", label: "Turnovers from Bad Passes" },
    { "value": "Turnovers LostBall", label: "Turnovers from Lost Balls" },
    { "value": "Fouls Committed Shoot", label: "Fouls Committed While Shooting" },
    { "value": "Fouls Committed Off.", label: "Fouls Committed on Offensive Plays" },
    { "value": "Fouls Drawn Shoot", label: "Fouls Drawn While Shooting" },
    { "value": "Fouls Drawn Off.", label: "Fouls Drawn on Offensive Plays" },
    { "value": "Misc. PGA", label: "Miscellaneous Points Generated by Assists" },
    { "value": "Misc. And1", label: "Miscellaneous And-1s" },
    { "value": "Misc. Blkd", label: "Miscellaneous Blocks" }
  ],
  'Playoffs': [
    { "value": "Totals G", label: "Games" },
    { "value": "Totals W", label: "Total Wins" },
    { "value": "Totals L", label: "Total Losses" },
    { "value": "Totals MP", label: "Total Minutes Played" },
    { "value": "Totals FG", label: "Total Field Goals Made" },
    { "value": "Totals FGA", label: "Total Field Goals Attempted" },
    { "value": "Totals 3P", label: "Total Three-Point Field Goals Made" },
    { "value": "Totals 3PA", label: "Total Three-Point Field Goals Attempted" },
    { "value": "Totals FT", label: "Total Free Throws Made" },
    { "value": "Totals FTA", label: "Total Free Throws Attempted" },
    { "value": "Totals ORB", label: "Total Offensive Rebounds" },
    { "value": "Totals TRB", label: "Total Rebounds" },
    { "value": "Totals AST", label: "Total Assists" },
    { "value": "Totals STL", label: "Total Steals" },
    { "value": "Totals BLK", label: "Total Blocks" },
    { "value": "Totals TOV", label: "Total Turnovers" },
    { "value": "Totals PF", label: "Total Personal Fouls" },
    { "value": "Totals PTS", label: "Total Points" },
    { "value": "Shooting FG%", label: "Shooting Field Goal Percentage" },
    { "value": "Shooting FT%", label: "Shooting Free Throw Percentage" },
    { "value": "Per Game MP", label: "Minutes Played Per Game" },
    { "value": "Per Game PTS", label: "Points Per Game" },
    { "value": "Per Game TRB", label: "Rebounds Per Game" },
    { "value": "Per Game AST", label: "Assists Per Game" }
  ],
  'Shooting': [
    { "value": "G", label: "Games" },
    { "value": "MP", label: "Minutes Played" },
    { "value": "FG%", label: "Field Goal Percentage" },
    { "value": "Dist.", label: "Distance" },
    { "value": "% of FGA by Distance 2P", label: "% of Field Goals Attempted by Distance 2P" },
    { "value": "% of FGA by Distance 0-3", label: "% of Field Goals Attempted by Distance 0-3 Feet" },
    { "value": "% of FGA by Distance 3-10", label: "% of Field Goals Attempted by Distance 3-10 Feet" },
    { "value": "% of FGA by Distance 10-16", label: "% of Field Goals Attempted by Distance 10-16 Feet" },
    { "value": "% of FGA by Distance 16-3P", label: "% of Field Goals Attempted by Distance 16 Feet to 3-Point Line" },
    { "value": "% of FGA by Distance 3P", label: "% of Field Goals Attempted by Distance 3-Point Line" },
    { "value": "FG% by Distance 2P", label: "Field Goal Percentage by Distance 2P" },
    { "value": "FG% by Distance 0-3", label: "Field Goal Percentage by Distance 0-3 Feet" },
    { "value": "FG% by Distance 3-10", label: "Field Goal Percentage by Distance 3-10 Feet" },
    { "value": "FG% by Distance 10-16", label: "Field Goal Percentage by Distance 10-16 Feet" },
    { "value": "FG% by Distance 16-3P", label: "Field Goal Percentage by Distance 16 Feet to 3-Point Line" },
    { "value": "FG% by Distance 3P", label: "Field Goal Percentage by Distance 3-Point Line" },
    { "value": "% of FG Ast'd 2P", label: "% of Field Goals Assisted for 2P" },
    { "value": "% of FG Ast'd 3P", label: "% of Field Goals Assisted for 3P" },
    { "value": "Dunks %FGA", label: "Dunks as % of Field Goals Attempted" },
    { "value": "Dunks #", label: "Number of Dunks" },
    { "value": "Corner 3s %3PA", label: "Corner 3-Point Shots as % of 3-Point Field Goals Attempted" },
    { "value": "Heaves Att.", label: "Number of Heaves Attempted" },
    { "value": "Heaves #", label: "Number of Heaves Made" }
  ]
};

const PlayerStatsChart = ({ data, type }) => {
  // State to keep track of the selected stats
  const [selectedStats, setSelectedStats] = useState([statOptions[type][0].value]);

  // Update selectedStats when type changes
  useEffect(() => {
    setSelectedStats([statOptions[type][0].value]);
  }, [type]);

  // Format data for the chart
  const formattedData = Object.keys(data).map(key => ({
    xValue: data[key].Date 
      ? moment(data[key].Date).format('DD MMM YYYY') 
      : data[key].Season, // Use Date if available, otherwise use Season
    ...selectedStats.reduce((acc, stat) => {
      acc[stat] = data[key][stat] || 0; // Include each selected stat in the data
      return acc;
    }, {})
  }));

  // Function to handle stat change from dropdown
  const handleStatChange = (selectedOptions) => {
    setSelectedStats(selectedOptions.map(option => option.value));
  };

  return (
    <div>
      <h3>Player Stats Over Time</h3>

      {/* Dropdown for selecting the stats */}
      <Select
        isMulti
        value={statOptions[type].filter(option => selectedStats.includes(option.value))}
        options={statOptions[type]}
        onChange={handleStatChange}
        className="dropdown"
      />

      {/* LineChart displaying the selected stats */}
      <ResponsiveContainer width="100%" height={400}>
        <LineChart data={formattedData}>
          <CartesianGrid strokeDasharray="3 3" />
          <XAxis dataKey="xValue" />
          <YAxis />
          <Tooltip />
          <Legend />
          {selectedStats.map(stat => (
            <Line
              key={stat}
              type="monotone"
              dataKey={stat}
              stroke={statColors[type][stat] || '#8884d8'} // Use predefined color or default
              activeDot={{ r: 8 }}
            />
          ))}
        </LineChart>
      </ResponsiveContainer>
    </div>
  );
};

export default PlayerStatsChart;
