const statOptions = {
  'Adjusted Shooting': [
    { value: 'Shooting % FG', label: 'FG%' },
    { value: 'Shooting % 2P', label: '2P%' },
    { value: 'Shooting % 3P', label: '3P%' },
    { value: 'Shooting % eFG', label: 'eFG%' },
    { value: 'Shooting % FT', label: 'FT%' },
    { value: 'Shooting % TS', label: 'TS%' },
    { value: 'Shooting % FTr', label: 'FTr' },
    { value: 'Shooting % 3PAr', label: '3PAr' },
    { value: 'League Shooting % FG', label: 'Lg FG%' },
    { value: 'League Shooting % 2P', label: 'Lg 2P%' },
    { value: 'League Shooting % 3P', label: 'Lg 3P%' },
    { value: 'League Shooting % eFG', label: 'Lg eFG%' },
    { value: 'League Shooting % FT', label: 'Lg FT%' },
    { value: 'League Shooting % TS', label: 'Lg TS%' },
    { value: 'League Shooting % FTr', label: 'Lg FTr' },
    { value: 'League Shooting % 3PAr', label: 'Lg 3PAr' },
  ],
  'Totals': [
    { value: 'G', label: 'Games' },
    { value: 'GS', label: 'Starts' },
    { value: 'MP', label: 'Minutes' },
    { value: 'FG', label: 'FG' },
    { value: 'FGA', label: 'FGA' },
    { value: 'FG%', label: 'FG%' },
    { value: '3P', label: '3P' },
    { value: '3PA', label: '3PA' },
    { value: '3P%', label: '3P%' },
    { value: '2P', label: '2P' },
    { value: '2PA', label: '2PA' },
    { value: '2P%', label: '2P%' },
    { value: 'eFG%', label: 'eFG%' },
    { value: 'FT', label: 'FT' },
    { value: 'FTA', label: 'FTA' },
    { value: 'FT%', label: 'FT%' },
    { value: 'ORB', label: 'ORB' },
    { value: 'DRB', label: 'DRB' },
    { value: 'TRB', label: 'REB' },
    { value: 'AST', label: 'AST' },
    { value: 'STL', label: 'STL' },
    { value: 'BLK', label: 'BLK' },
    { value: 'TOV', label: 'TO' },
    { value: 'PF', label: 'PF' },
    { value: 'PTS', label: 'PTS' }
  ],
  'Advanced': [
    { value: 'G', label: 'Games' },
    { value: 'MP', label: 'Minutes' },
    { value: 'PER', label: 'PER' },
    { value: 'TS%', label: 'TS%' },
    { value: '3PAr', label: '3PAr' },
    { value: 'FTr', label: 'FTr' },
    { value: 'ORB%', label: 'ORB%' },
    { value: 'DRB%', label: 'DRB%' },
    { value: 'TRB%', label: 'REB%' },
    { value: 'AST%', label: 'AST%' },
    { value: 'STL%', label: 'STL%' },
    { value: 'BLK%', label: 'BLK%' },
    { value: 'TOV%', label: 'TO%' },
    { value: 'USG%', label: 'USG%' },
    { value: 'OWS', label: 'OWS' },
    { value: 'DWS', label: 'DWS' },
    { value: 'WS', label: 'WS' },
    { value: 'WS/48', label: 'WS/48' },
    { value: 'OBPM', label: 'OBPM' },
    { value: 'DBPM', label: 'DBPM' },
    { value: 'BPM', label: 'BPM' },
    { value: 'VORP', label: 'VORP' }
  ],
  'Highs': [
    { value: 'Game Highs FG', label: 'FG' },
    { value: 'Game Highs FGA', label: 'FGA' },
    { value: 'Game Highs 3P', label: '3P' },
    { value: 'Game Highs 3PA', label: '3PA' },
    { value: 'Game Highs 2P', label: '2P' },
    { value: 'Game Highs 2PA', label: '2PA' },
    { value: 'Game Highs FT', label: 'FT' },
    { value: 'Game Highs FTA', label: 'FTA' },
    { value: 'Game Highs ORB', label: 'ORB' },
    { value: 'Game Highs DRB', label: 'DRB' },
    { value: 'Game Highs TRB', label: 'REB' },
    { value: 'Game Highs AST', label: 'AST' },
    { value: 'Game Highs STL', label: 'STL' },
    { value: 'Game Highs BLK', label: 'BLK' },
    { value: 'Game Highs TOV', label: 'TO' },
    { value: 'Game Highs PF', label: 'PF' },
    { value: 'Game Highs PTS', label: 'PTS' },
    { value: 'Game Highs GmSc', label: 'GmSc' }
  ],
  'Individual Game Data': [
    { value: 'MP', label: 'Minutes' },
    { value: 'FG', label: 'FG' },
    { value: 'FGA', label: 'FGA' },
    { value: 'FG%', label: 'FG%' },
    { value: '3P', label: '3P' },
    { value: '3PA', label: '3PA' },
    { value: '3P%', label: '3P%' },
    { value: 'FT', label: 'FT' },
    { value: 'FTA', label: 'FTA' },
    { value: 'FT%', label: 'FT%' },
    { value: 'ORB', label: 'ORB' },
    { value: 'DRB', label: 'DRB' },
    { value: 'TRB', label: 'REB' },
    { value: 'AST', label: 'AST' },
    { value: 'STL', label: 'STL' },
    { value: 'BLK', label: 'BLK' },
    { value: 'TOV', label: 'TO' },
    { value: 'PF', label: 'PF' },
    { value: 'PTS', label: 'PTS' },
    { value: 'GmSc', label: 'GmSc' },
    { value: '+/-', label: '+/-' }
  ],
  'Per Game': [
    { "value": "G", "label": "Gms" },
    { "value": "GS", "label": "GS" },
    { "value": "MP", "label": "MP" },
    { "value": "FG", "label": "FGM" },
    { "value": "FGA", "label": "FGA" },
    { "value": "FG%", "label": "FG%" },
    { "value": "3P", "label": "3PM" },
    { "value": "3PA", "label": "3PA" },
    { "value": "3P%", "label": "3P%" },
    { "value": "2P", "label": "2PM" },
    { "value": "2PA", "label": "2PA" },
    { "value": "2P%", "label": "2P%" },
    { "value": "eFG%", "label": "eFG%" },
    { "value": "FT", "label": "FTM" },
    { "value": "FTA", "label": "FTA" },
    { "value": "FT%", "label": "FT%" },
    { "value": "ORB", "label": "ORB" },
    { "value": "DRB", "label": "DRB" },
    { "value": "TRB", "label": "TRB" },
    { "value": "AST", "label": "AST" },
    { "value": "STL", "label": "STL" },
    { "value": "BLK", "label": "BLK" },
    { "value": "TOV", "label": "TOV" },
    { "value": "PF", "label": "PF" },
    { "value": "PTS", "label": "PTS" }
  ],
  'Per 36 Minutes': [
    { "value": "FG", "label": "FGM" },
    { "value": "FGA", "label": "FGA" },
    { "value": "FG%", "label": "FG%" },
    { "value": "3P", "label": "3PM" },
    { "value": "3PA", "label": "3PA" },
    { "value": "3P%", "label": "3P%" },
    { "value": "2P", "label": "2PM" },
    { "value": "2PA", "label": "2PA" },
    { "value": "2P%", "label": "2P%" },
    { "value": "FT", "label": "FTM" },
    { "value": "FTA", "label": "FTA" },
    { "value": "FT%", "label": "FT%" },
    { "value": "ORB", "label": "ORB" },
    { "value": "DRB", "label": "DRB" },
    { "value": "TRB", "label": "TRB" },
    { "value": "AST", "label": "AST" },
    { "value": "STL", "label": "STL" },
    { "value": "BLK", "label": "BLK" },
    { "value": "TOV", "label": "TOV" },
    { "value": "PF", "label": "PF" },
    { "value": "PTS", "label": "PTS" }
  ],
  'Per Possesion': [
    { "value": "G", "label": "Gms" },
    { "value": "GS", "label": "GS" },
    { "value": "MP", "label": "MP" },
    { "value": "FG", "label": "FGM" },
    { "value": "FGA", "label": "FGA" },
    { "value": "FG%", "label": "FG%" },
    { "value": "3P", "label": "3PM" },
    { "value": "3PA", "label": "3PA" },
    { "value": "3P%", "label": "3P%" },
    { "value": "2P", "label": "2PM" },
    { "value": "2PA", "label": "2PA" },
    { "value": "2P%", "label": "2P%" },
    { "value": "FT", "label": "FTM" },
    { "value": "FTA", "label": "FTA" },
    { "value": "FT%", "label": "FT%" },
    { "value": "ORB", "label": "ORB" },
    { "value": "DRB", "label": "DRB" },
    { "value": "TRB", "label": "TRB" },
    { "value": "AST", "label": "AST" },
    { "value": "STL", "label": "STL" },
    { "value": "BLK", "label": "BLK" },
    { "value": "TOV", "label": "TOV" },
    { "value": "PF", "label": "PF" },
    { "value": "PTS", "label": "PTS" },
    { "value": "ORtg", "label": "ORtg" },
    { "value": "DRtg", "label": "DRtg" }
  ],
  'Play By Play': [
    { "value": "G", "label": "Gms" },
    { "value": "MP", "label": "MP" },
    { "value": "Position Estimate PF%", "label": "PF%" },
    { "value": "Position Estimate C%", "label": "C%" },
    { "value": "+/- Per 100 Poss. OnCourt", "label": "+/- OnCourt" },
    { "value": "+/- Per 100 Poss. On-Off", "label": "+/- On-Off" },
    { "value": "Turnovers BadPass", "label": "TO BadPass" },
    { "value": "Turnovers LostBall", "label": "TO LostBall" },
    { "value": "Fouls Committed Shoot", "label": "Fouls Shoot" },
    { "value": "Fouls Committed Off.", "label": "Fouls Off." },
    { "value": "Fouls Drawn Shoot", "label": "Fouls Drawn Shoot" },
    { "value": "Fouls Drawn Off.", "label": "Fouls Drawn Off." },
    { "value": "Misc. PGA", "label": "Misc. PGA" },
    { "value": "Misc. And1", "label": "Misc. And1" },
    { "value": "Misc. Blkd", "label": "Misc. Blkd" }
  ],
  'Playoffs': [
    { "value": "Totals G", "label": "Gms" },
    { "value": "Totals W", "label": "W" },
    { "value": "Totals L", "label": "L" },
    { "value": "Totals MP", "label": "MP" },
    { "value": "Totals FG", "label": "FGM" },
    { "value": "Totals FGA", "label": "FGA" },
    { "value": "Totals 3P", "label": "3PM" },
    { "value": "Totals 3PA", "label": "3PA" },
    { "value": "Totals FT", "label": "FTM" },
    { "value": "Totals FTA", "label": "FTA" },
    { "value": "Totals ORB", "label": "ORB" },
    { "value": "Totals TRB", "label": "TRB" },
    { "value": "Totals AST", "label": "AST" },
    { "value": "Totals STL", "label": "STL" },
    { "value": "Totals BLK", "label": "BLK" },
    { "value": "Totals TOV", "label": "TOV" },
    { "value": "Totals PF", "label": "PF" },
    { "value": "Totals PTS", "label": "PTS" },
    { "value": "Shooting FG%", "label": "FG%" },
    { "value": "Shooting FT%", "label": "FT%" },
    { "value": "Per Game MP", "label": "MP/G" },
    { "value": "Per Game PTS", "label": "PTS/G" },
    { "value": "Per Game TRB", "label": "TRB/G" },
    { "value": "Per Game AST", "label": "AST/G" }
  ],
  'Shooting': [
    { "value": "G", "label": "Gms" },
    { "value": "MP", "label": "MP" },
    { "value": "FG%", "label": "FG%" },
    { "value": "Dist.", "label": "Dist." },
    { "value": "% of FGA by Distance 2P", "label": "% FGA 2P" },
    { "value": "% of FGA by Distance 0-3", "label": "% FGA 0-3" },
    { "value": "% of FGA by Distance 3-10", "label": "% FGA 3-10" },
    { "value": "% of FGA by Distance 10-16", "label": "% FGA 10-16" },
    { "value": "% of FGA by Distance 16-3P", "label": "% FGA 16-3P" },
    { "value": "% of FGA by Distance 3P", "label": "% FGA 3P" },
    { "value": "FG% by Distance 2P", "label": "FG% 2P" },
    { "value": "FG% by Distance 0-3", "label": "FG% 0-3" },
    { "value": "FG% by Distance 3-10", "label": "FG% 3-10" },
    { "value": "FG% by Distance 10-16", "label": "FG% 10-16" },
    { "value": "FG% by Distance 16-3P", "label": "FG% 16-3P" },
    { "value": "FG% by Distance 3P", "label": "FG% 3P" },
    { "value": "% of FG Ast'd 2P", "label": "% FG Ast'd 2P" },
    { "value": "% of FG Ast'd 3P", "label": "% FG Ast'd 3P" },
    { "value": "Dunks %FGA", "label": "Dunks % FGA" },
    { "value": "Dunks #", "label": "Dunks #" },
    { "value": "Corner 3s %3PA", "label": "Corner 3s % 3PA" },
    { "value": "Heaves Att.", "label": "Heaves Att." },
    { "value": "Heaves #", "label": "Heaves #" }
  ]
  
};

export default statOptions;